### ISSUE TITLE
3.0.1: transaction not sphinx 4.0.x ready?

### ISSUE THREAD

**Issue by kloczek** [zopefoundation/transaction#106]
Looks like it is some issue with way of using sphinx
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.2

Extension error:
Could not import extension repoze.sphinx.autointerface (exception: cannot import name 'force_decode' from 'sphinx.util' (/usr/lib/python3.8/site-packages/sphinx/util/__init__.py))
```

**Comment by jamadden** [comment]
> Or it is repoze.sphinx.autointerface module issue?

Yes. But you probably already know that because you opened https://github.com/repoze/repoze.sphinx.autointerface/issues/18 (even though it duplicated the already open https://github.com/repoze/repoze.sphinx.autointerface/issues/16).

**Comment by kloczek** [comment]
I forgot about that :P

**Comment by mgedmin** [comment]
We've been adding `Sphinx < 4.0` to `[toxenv:docs]` in various projects as a workaround for now.

**Comment by icemac** [comment]
In #102 we pinned to `Sphinx < 4.0`, this is needed until `repoze.sphinx.autointerface` is fixed. So closing this issue here.
