### ISSUE TITLE
Print the stack when a resource manager joins a transaction

### ISSUE THREAD

**Issue by mwatts15** [zopefoundation/transaction#108]
For read-only ZODB connections, I sometimes have the problem that I've accidentally modified the database, causing an error when the transaction commits. Tracking down the offending operation is easy enough, but it requires modifying either `transaction` or `ZODB`, which is somewhat inconvenient. It would be nice to either have a logger (i.e., as defined in the `logging` module) that prints the stack when a transaction is joined. The logger could be disabled by default.

**Comment by jamadden** [comment]
It's possible to do this in client code without any changes to this package, so it can be customized to exactly what you need. Here's a basic example (omitting some things around interface declarations and whether or not transaction object identity matters):

```python
# tx.py
import transaction
import traceback

class TransactionProxy(object):

    def __init__(self, tx):
        self.__tx = tx

    def __getattr__(self, name):
        # Delegate unknown to the real transaction
        return getattr(self.__tx, name)

    def join(self, resource):
        print("Resource", resource, "joined transaction", self.__tx)
        traceback.print_stack()
        return self.__tx.join(resource)

class TransactionManagerProxy(object):

    def __init__(self, mgr):
        self.__mgr = mgr

    def begin(self):
        return TransactionProxy(self.__mgr.begin())

    def get(self):
        return TransactionProxy(self.__mgr.get())

    @property
    def manager(self):
        # If we don't pass a TransactionManager to DB.open(), ZODB
        # uses the global transaction manager, but unwraps the thread
        # local proxy to allow closing from alternate threads.
        return TransactionManagerProxy(self.__mgr.manager)

    def __getattr__(self, name):
        return getattr(self.__mgr, name) # Likewise delegate

# Do this early in startup
transaction.manager = mgr = TransactionManagerProxy(transaction.manager)
transaction.get = mgr.get
transaction.begin = mgr.begin

# Now an example showing it works
from ZODB import DB
db = DB(None)
transaction.begin()
conn = db.open()
conn.root.thing = object() # <== line 50
transaction.commit()
conn.close()
```

```console
$ python tx.py
Resource <Connection at 10d50e780> joined transaction <transaction._transaction.Transaction object at 0x10cdf6be0>
  File "/tmp/tx.py", line 50, in <module>
    conn.root.thing = object()
  File "//ZODB/Connection.py", line 1271, in __setattr__
    self._root[name] = v
  File "//persistent/mapping.py", line 85, in __setitem__
    self._p_changed = 1
  File "//ZODB/Connection.py", line 830, in register
    self._register(obj)
  File "//ZODB/Connection.py", line 840, in _register
    self.transaction_manager.get().join(self)
  File "tx.py", line 16, in join
    traceback.print_stack()
```

**Comment by icemac** [comment]
@jamadden Thank you for answering this question.
@mwatts15 Does the answer solve the issue for you?

**Comment by mwatts15** [comment]
@jamadden, thanks. I would prefer if I and other coders didn't have to modify any code to have access to this capability. Not all of our code will use the shared transaction manager, and needing a wrapper means you have to track down where the transaction manager is being created. I think this is something that is generally useful, so it would be good to have the capability built-in to `transaction`.

**Comment by d-maurer** [comment]
Mark Watts wrote at 2022-1-25 19:02 -0800:
***@***.***, thanks. I would prefer if I and other coders didn't have to modify any code to have access to this capability. Not all of our code will use the shared transaction manager, and needing a wrapper means you have to track down where the transaction manager is being created. I think this is something that is generally useful, so it would be good to have the capability built-in to `transaction`.

You likely need this feature only in very rare and special situations.
For rare and special situations, you can use special/unconventional means.
All features come with a cost: design, implementation, test, documentation,
maintenance. Those costs are often not justified for features
used only in special situations.

A few days ago, I used a debugger to find out why a transaction
supposed to be read only modifies persistent data.

Should you need stack information for `Transaction.join` more regularly,
you could "monkey patch" this method.
