### ISSUE TITLE
Add support for QA tooling?

### ISSUE THREAD

**Issue by jenstroeger** [zopefoundation/transaction#110]
Would there be interest in adding support for QA tools (e.g. [pylint](http://pylint.pycqa.org/) or [black](https://github.com/psf/black)), and perhaps some more CI and automation? See also the [python-package-template](https://github.com/jenstroeger/python-package-template) repo for more details.

I also noticed that this package still [has support for Python 3.5 and 3.6](https://github.com/zopefoundation/transaction/blob/647880ba7f705b2a2cea0e860899d5231b9ffc8f/setup.py#L71)  both of which have reached EOL and are no longer supported. Should this package adjust accordingly?

**Comment by jugmac00** [comment]
There is no interest in adding more tooling nor dropping Python versions.

Cf black: https://github.com/zopefoundation/meta/issues/6

Cf Python versions: 
https://www.zope.dev/developer/roadmap.html

Cf pylint:
It is slow and causes so many false positives

**Comment by jenstroeger** [comment]
> Cf pylint:
> It is slow and causes so many false positives

Huh 😳 I’d argue it’s worth the effort and results should be reviewed and considered carefully; pylint catches subtle problems as well. People seem to lint the code anyway (see PR https://github.com/zopefoundation/transaction/pull/97), so why not make it official?

**Comment by d-maurer** [comment]
Jens Tröger wrote at 2022-4-4 18:19 -0700:
>> Cf pylint:

>> It is slow and causes so many false positives

>

>Huh ? I’d argue it’s worth the effort and results should be reviewed and considered carefully; pylint catches subtle problems as well. People seem to lint the code anyway (see PR https://github.com/zopefoundation/transaction/pull/97), so why not make it official?


-1
A significant part of my commits have the message "make flake8|isort happy":
they mark changes I consider cosmetic (rather than essential)
(prominent examples are "overindented continuation line",
"inline comments require 2 spaces", ...).
I would not be happy to add "make pylint happy".
