### ISSUE TITLE
gevent.local.local breaks transaction.manager

### ISSUE THREAD

**Issue by miohtama** [zopefoundation/transaction#21]
This is not an issue with `transaction` per se, but an evil gotcha that might happen when one is using `transaction` with other libraries.

gevent is a coroutine based Python networking library. gevent offers functionality to make stdlib more co-routine friendly by monkey patching stdlib:

    >>> import threading
    >>> threading.local
    <class '_thread._local'>

    >>> from gevent import monkey
    >>> gevent.monkey.patch_all()
    >>> threading.local
    <class 'gevent.local.local'>

Transaction has `ThreadTransactionManager` class that inherits from `threading.local`. If used in an environment where something has run `gevent.monkey.patch_all()` `ThreadTransactionManager` ceases to function properly and shares transactions across thread boundaries. This may be subtle breakage; one might not run issues until some race condition timing occurs.

I am currently figuring out if `gevent` can be made play nicely with `transaction` if they co-exist within the same process.

**Comment by jamadden** [comment]
Hi! I'm a maintainer of gevent and I've also contributed to this library. My organization runs a gevent-patched system that heavily uses `transaction` and I don't recall that we've run into any trouble. I also don't think we have any special code, aside from an assert in one of our modules:
```python
assert issubclass(transaction.ThreadTransactionManager, gevent.local.local)
```

This makes sure that the monkey-patching has been done soon enough. The trick, as gevent tries to document, is to make sure that monkey-patching is done *immediately* during process startup, before any other imports. In our case, we have modified `pserve` to do the patching, but that might differ in a given environment.

Our assert code is slightly more general than that to account for other thread-local things we're aware of. I can share it if that would be helpful.

**Comment by miohtama** [comment]
@jamadden Here is the description of the sympton: ThreadTransactionManager gives same `_txn` even if the thread differs.

    Thread is <ServiceThread(xxx, started 4449301920)>, manager is <transaction._manager.ThreadTransactionManager object at 0x1072e0e88>, Tx is <transaction._transaction.Transaction object at 0x109373fd0>
    Thread is <ServiceThread(yyy, started 4449302072)>, manager is <transaction._manager.ThreadTransactionManager object at 0x1072e0e88>, Tx is <transaction._transaction.Transaction object at 0x109373fd0>

This is using threads started with `threading.Thread.start`.

I'd assume I need to get patched `threading.Thread`?

**Comment by miohtama** [comment]
I moved `gevent.monkey.patch_all()` to very early in my program and managed to resolve the issue.
