### ISSUE TITLE
add a public api for tracking attempts

### ISSUE THREAD

**Issue by mmerickel** [zopefoundation/transaction#36]
The `manager.run(attempts)` api is awesome.  I'd like to use it in pyramid_tm which currently re-implements most of the logic itself. There's one feature that would be really useful which is a public api on the transaction (or the manager) to expose what's happening to underlying code.

Specifically we have some cases where we'd like to do things differently on the last attempt than on earlier attempts that raise retryable exceptions and there's no way to know that we're on the last attempt using the current `run` api.

I'd propose something like `txn.is_last_attempt` or `txn.attempt_index` combined with `txn.max_attempts` or `txn.attempts_remaining`. This would allow underlying code to make decisions on what it does with retryable exceptions.

I'm happy to work on a PR for this but wanted to get some input on the API first. Personally I prefer `txn.is_last_attempt` as I don't have an explicit need to expose the exact number of attempts to underlying code.

**Comment by jimfulton** [comment]
Thanks for the suggestion and offer to create a PR!

Would you mind bringing this up here:

https://groups.google.com/forum/#!forum/python-transaction

?

**Comment by mmerickel** [comment]
I'll close this based on comments from the mailing list. I appreciate the bw-compat issues in that not every use-case expects an attempt model.
