### ISSUE TITLE
add a public api for manager._retryable

### ISSUE THREAD

**Issue by mmerickel** [zopefoundation/transaction#37]
In a web context we want to wrap as much of the request as possible, but we also want to render errors. This causes a circular dependency between the transaction manager and the system that renders errors.

In pyramid_tm the goal is to expose to the underlying code whether it is processing a retryable error and allow it to handle such errors differently if it wants. If we choose to handle the retryable error then we are effectively squashing the exception and thus the `transaction.run()` will see it as valid. I'd like to allow pyramid_tm to detect the retryable errors itself and raise exceptions if necessary. This depends on `manager._retryable` right now, but I'd be happier about it if the API itself were public.

A public api would make sense as well as it's intended to be an abstraction around retryable errors... without it each error handler in an app needs to check for arbitrary exceptions on a case-by-case basis instead of just checking that they are retryable.

Would `manager.is_retryable(error)` work? The `error_type` seems redundant to me. I'm happy to make the PR myself.

**Comment by jimfulton** [comment]
Again, it would be good to bring this up here: https://groups.google.com/forum/#!forum/python-transaction

**Comment by jimfulton** [comment]
My sense is that this is all too complicated. :)

**Comment by mmerickel** [comment]
> My sense is that this is all too complicated. :)

Well it's not easy.. but neither is solving something that no one seems to want to think about and has been broken for as long as I've been using WSGI frameworks.

Honestly I wouldn't even be asking for the public APIs because pyramid_tm has been using private ones forever (Chris wasn't as worried about that since he has commit access to these repos). I wasn't even aware they were maintained until transaction 2.0 broke pyramid_tm.

Anyway I will post my story to the mailing list as well, but the motivations are also available in https://github.com/Pylons/pyramid_tm/issues/40 and https://github.com/Pylons/pyramid_tm/pull/42.

Should this issue tracker be closed/hidden if all discussion happens on the mailing list?

**Comment by jimfulton** [comment]
We can keep this open until after we discuss on the list.
