### ISSUE TITLE
Document exception semantics for hooks

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/transaction#49]
In particular, the `_before_commit` hooks are not expected to raise exceptions, and if they do so, leave the transaction in an ambiguous state (`commit` not called, hooks not cleared, but one or more hooks may have completed).

See: https://github.com/Pylons/pyramid_tm/issues/63

**Comment by davisagli** [comment]
Another one that has caught me is that exceptions in after-commit hooks are swallowed.
