### ISSUE TITLE
Joining a committing transaction

### ISSUE THREAD

**Issue by elliot-jsq** [zopefoundation/transaction#52]
Hi, I stumbled upon the following comment when digging around as to why I was getting an exception:
```python
            # TODO: Should it be possible to join a committing transaction?
            # I think some users want it.
```
I don't know if this is the appropriate forum for this, but I am a user who wants this. I can elaborate on my use case if it matters.

**Comment by d-maurer** [comment]
@elliot-jsq 
> I can elaborate on my use case if it matters.

Yes, please. Please check in addition, if your use case could not be satisfied with a "before commit hook" or a "synchronizer".

**Comment by elliot-jsq** [comment]
@d-maurer I eventually took a less good solution to my problem. Unfortunately, I can no longer remember the minutiae of my specific issue (as it was over a year ago at this point). I do remember before commit hooks were not sufficient, but I am unfamiliar with synchronizers, so maybe that would have solved my issue? Sorry I can't elaborate more anymore. Would that my memory were better...
