### ISSUE TITLE
Documentation is unhelpful for complete newcomers

### ISSUE THREAD

**Issue by hynek** [zopefoundation/transaction#53]
I’ve tried to figure out whether transaction could help me in one of my projects, and the documentation left me completely baffled. It seems to be mostly a bunch of maintainer notes?

Things I noticed as a first-time reader:

- The first sentence is “Transaction objects manage resources for an individual activity.” – that doesn’t tell me any more than the package name.
- The first section is a ZOPE  compatibility notice. I guess at this point you lose 90% of readers because it makes the lib look like a ZOPE implementation detail.
- Next some low-level concepts are outlined without any explanation how they fit together.
- And with that you’re thrown into the meat of the documentation that doesn’t make any sense whatsoever without understanding what the lib is about and how things fit together.
- Especially egregious are the chapters on how to write DataManagers and ResourceManagers without explaining what they are (I still have no clue) or why I’d want to implement them.
    - Bonus points for saying `This transaction.tests.examples.DataManager class provides a trivial data-manager implementation and docstrings to illustrate the the protocol and to provide a tool for writing tests.` while there isn’t a single docstring beyond `Used by the 'datamanager' chapter in the Sphinx docs.`. :)
    - it would also be nice to [link](https://github.com/zopefoundation/transaction/blob/master/transaction/tests/examples.py) to it

All that to say is that I care because I know that most of the zope libraries a best of breed and it would be a pity if people re-implemented their functionality (poorly), just because they couldn’t figure out how to use them.

I understand this issue is not just one issue, so feel free to handle however you want it.

**Comment by jimfulton** [comment]
First of all, sorry for the slow reply.

Second, I couldn't agree more!

I brought this up a year ago:

https://groups.google.com/forum/#!topic/python-transaction/hNoAk9lItRo

As noted there, there's material we could start with (at least):

https://github.com/cguardia/ZODB-Documentation/blob/master/book/transactions.rst

But no one stepped up and I didn't find the time (and forgot about it).

I wonder if @cguardia would be willing to help out here.

**Comment by cguardia** [comment]
I can help, what do you need me to do? Would be much easier for me if
there's a plan I can follow.

Carlos de la Guardia

**Comment by jimfulton** [comment]
Thanks Carlos!

Here's what I'd like to see initially:

1. Take the user focussed parts of:

    https://github.com/cguardia/ZODB-Documentation/blob/master/book/transactions.rst

    and make that the front page, index.rst, of the current transaction documentation.

2. Move the existing content to a developer section.

3. Move the table of contents to a contents.rst (so the table of contents doesn't clutter the front page).

This would make the documentation not suck.

**Comment by cguardia** [comment]
Hi,

I did these changes. Is it possible to get commit access to the repository
to create my PR?

Thanks,

Carlos de la Guardia

**Comment by jimfulton** [comment]
On Wed, Feb 28, 2018 at 10:55 PM, Carlos de la Guardia <
notifications@github.com> wrote:

> I did these changes. Is it possible to get commit access to the repository
> to create my PR?
>

I'm surprised you aren't a committer already. Did you ever submit a
committer agreement?

**Comment by cguardia** [comment]
I did. Years ago.

Carlos de la Guardia

**Comment by tseaver** [comment]
I have invited Carlos to the two relevant teams.

**Comment by cguardia** [comment]
Thanks! PR created.

Carlos de la Guardia

**Comment by cguardia** [comment]
@jimfulton should I just merge this?

**Comment by jimfulton** [comment]
It would be great if someone reviewed it. :)  If you don't get a review by next week, then go ahead.

Thanks!

**Comment by cguardia** [comment]
This was addresed here:

https://github.com/zopefoundation/transaction/commit/f1a88757e2dc4c71f724e2d23efad04e6906bdd7

**Comment by jimfulton** [comment]
Thanks @cguardia ! This is a huge improvement.
