### ISSUE TITLE
Transactions with multiprocessing

### ISSUE THREAD

**Issue by BlueManCZ** [zopefoundation/transaction#61]
Hello, can I somehow use transactions with shared `transaction.manager` from multiple processes?

For example, I have two processes incrementing counter in for loop:
```
def worker():
    for i in range(0, 10000):
        counter.value += 1
```
And I want commit result of incrementation by transaction like this:
```
def worker():
    with transaction.manager:
        for i in range(0,10000):
            counter.value += 1
        transaction.commit()
```
But I think this code creates local `transaction.manager` for each process. Can I somehow share it?

**Comment by jimfulton** [comment]
The short answer is no. Data structures aren't shared across subprocesses.

Perhaps if you describe what you're trying to do, we can offer other suggestions. If you ask on the transaction (or ZODB) mailing list, others can benefit from the discussion.

**Comment by jamadden** [comment]
The asked question has been answered, and the remaining discussion, if any, has been directed to a mailing list, so I'll go ahead and close this issue.
