### ISSUE TITLE
Question: How to find a transaction’s data manager, if any?

### ISSUE THREAD

**Issue by jenstroeger** [zopefoundation/transaction#62]
What is the recommended way to check whether a custom data manager has [joined](https://transaction.readthedocs.io/en/latest/api.html#transaction.interfaces.ITransaction.join) a transaction’s set of registered data managers?

Currently I am using a transaction’s [extensions](https://transaction.readthedocs.io/en/latest/api.html#transaction.interfaces.ITransaction.extension) dictionary, but that feels somewhat flimsy:
```python
tm = transaction.manager  # Get the thread-local transaction manager.
try:
    tx = tm.get()
except Exception:  # transaction.interfaces.NoTransaction
    …  # No transaction available, do something.
else:
    if "SuperDataManager" not in tx.extension:
        # See also https://github.com/zopefoundation/transaction/issues/47
        dm = SuperDataManager(tm)
        tx.join(dm)
        tx.setExtendedInfo("SuperDataManager", dm)
    else:
        dm = tx.extension["SuperDataManager"] 
    dm.queue_my_data(some_data)
finally:
    pass
```
It seems to me that data managers are stored in a private list:
https://github.com/zopefoundation/transaction/blob/501a2934a1031f4def92701a44ebca8a317dd8a6/transaction/_transaction.py#L89
and checking whether a given data manager exists might be as simple as
```python
def get_joined(data_manager_type):
    """
    Return the data manager of type `data_manager_type` if it has joined this transaction, 
    or None if it hasn’t.
    """
    return next((_ for _ in self._resources if isinstance(_, data_manager_type)), None)
```
which would simplify the above code:
```python
dm = tx.get_joined(SuperDataManager)
if not dm:
    # See also https://github.com/zopefoundation/transaction/issues/47
    dm = SuperDataManager(tm)
    tx.join(dm)
dm.queue_my_data(some_data)
```
If I was to make the `SuperDataManager` [thread-local](https://docs.python.org/3/library/threading.html#thread-local-data) like the [default transaction manager](https://github.com/zopefoundation/transaction/blob/501a2934a1031f4def92701a44ebca8a317dd8a6/transaction/_manager.py#L212-L216), then I could also compare by the dm’s [object `id()`](https://docs.python.org/3/library/functions.html#id) directly.

**Comment by d-maurer** [comment]
The typical approach is to let the data manager remember whether it has already joined the transaction or not.

Of course, this requires a different handling of the data manager. In your code above, you (ab)use the transaction itself to manage the data manager. Typically, the data manager exists independent of the transaction (it may e.g. be managed in a thread local "variable"). The application interacts primarily with the data manager (transactions are relevant only at very few points) and the data manager decides when to join the transaction (and knows if it has already done this). If the data manager has joined the transaction, it will get informed when the transaction is aborted/committed (which implicitly creates a new transaction). It can then reset its `joined` state).
