### ISSUE TITLE
'ThreadTransactionManager' object has no attribute '_retryable'

### ISSUE THREAD

**Issue by julienmeyer** [zopefoundation/transaction#70]
Hello,
Since upgrade to version 2.4, i have the following error "'ThreadTransactionManager' object has no attribute '_retryable'". I'm using pyramid, sqlalchemy and pyramid_tm. The problem occurs in my functional tests where I use ThreadTransactionManager instead of Zope transaction manager.
I think that the function "_retryable" has been removed in this pull request https://github.com/zopefoundation/transaction/pull/68
Is it a bug or a mistake in the transaction lib or should I modify some thing in my sqlalchemy configuration ?
Thanks,
Julien

**Comment by jamadden** [comment]
Thanks for the report. `_retryable` was a private implementation detail. It was removed deliberately. `pyramid_tm` has already released a fix in 2.2.1 if you're seeing https://github.com/Pylons/pyramid_tm/issues/67
