### ISSUE TITLE
RTD integration broken

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/transaction#87]
Github services have been deprecated, and the existing service for RTD cannot be re-activated. Hence, docs aren't getting built. It needs migrated to [a webhook](https://docs.readthedocs.io/en/stable/webhooks.html). To do that, we need the project's ID, which is only available to the RTD admin. Could @tseaver please take a look?

**Comment by tseaver** [comment]
I *think* I've set up the webhook correctly.

**Comment by tseaver** [comment]
I just made a trivial edit to `rtd.txt` and pushed it on the `master` branch, triggering [this build](https://readthedocs.org/projects/transaction/builds/10087856/).
